/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue;

import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author pierrecharbit
 */
public class CardPanelZoom2 extends CardPanel2 {

	/**
	 * Creates new form ZoomCardPanel
	 */
	public CardPanelZoom2() {
		initComponents();
		Dimension dim = new Dimension(2*GamePanel.CARDWIDTH,2*GamePanel.CARDHEIGHT);
		this.setPreferredSize(dim);
	}

	
	@Override
	public void repaint() {
		if(c!=null){
			labelCout.setVisible(true);
			labelForce.setVisible(true);
			labelCout.setText("" + c.getCout());
			labelForce.setText("" + c.getValeur());
			labelNom.setText(c.getNom());
			jTextPane1.setText(c.getDescription());			
		}
		else if(labelCout!=null){
			labelCout.setVisible(false);
			labelForce.setVisible(false);
		}
	}
	
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelCout = new javax.swing.JLabel();
        labelForce = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        //labelCout.setBackground(new java.awt.Color(51, 51, 255));
        labelCout.setBackground(java.awt.Color.yellow);
        labelCout.setFont(new java.awt.Font("Helvetica Neue", Font.BOLD, 14)); // NOI18N
        //labelCout.setForeground(new java.awt.Color(255, 255, 255));
        labelCout.setForeground(java.awt.Color.black);
        labelCout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCout.setOpaque(true);

        //labelForce.setBackground(new java.awt.Color(255, 153, 0));
        labelForce.setBackground(java.awt.Color.blue);
        labelForce.setFont(new java.awt.Font("Helvetica Neue", Font.BOLD, 14)); // NOI18N
        //labelForce.setForeground(new java.awt.Color(255, 255, 255));
        labelForce.setForeground(java.awt.Color.black);
        labelForce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelForce.setOpaque(true);

        labelNom.setFont(new java.awt.Font("Helvetica Neue", Font.BOLD, 12)); // NOI18N
        labelNom.setForeground(java.awt.Color.black);
        labelNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(java.awt.Color.yellow);
        jTextPane1.setFont(new java.awt.Font("Helvetica Neue", Font.BOLD, 18));
        jTextPane1.setForeground(java.awt.Color.black);
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelCout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(labelForce, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(labelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelCout, labelForce});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCout, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(labelForce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelCout, labelForce});

    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelCout;
    private javax.swing.JLabel labelForce;
    private javax.swing.JLabel labelNom;
    // End of variables declaration                   
}
